repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff-format
        name: Ruff Format Check
        args: [--check]

      - id: ruff
        name: Ruff Lint
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: Mypy Typecheck
        additional_dependencies: [lark==1.3.1, types-docutils, sphinx, docutils]
        files: ^src/asciidoctrine/
        args: [--strict-optional]

  - repo: local
    hooks:
      - id: run-tck-coverage-check
        name: TCK Coverage Check
        entry: ./run-tck-coverage.sh
        language: script
        pass_filenames: false
        types: [python]
        stages: [manual] # Only run manually or in CI, too slow for commit hook

      - id: run-doctests
        name: Asciidoctor Doctests
        entry: env RUN_DOCTESTS=1 venv/bin/pytest tests/test_doctest_parsing.py
        language: system
        pass_filenames: false
        types: [python]
