[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asciidoctrine"
version = "0.1.0"
authors = [
  { name = "Michael R. Bernstein", email = "zopemaven@gmail.com" },
]
description = "A high-performance, pure-Python AsciiDoc parser based on Lark."
readme = { file = "README.adoc", content-type = "text/plain" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Text Processing :: Markup",
]
dependencies = [
    "lark>=1.1.0",
]

[project.urls]
"Homepage" = "https://github.com/webmaven/asciidoctrine"
"Bug Tracker" = "https://github.com/webmaven/asciidoctrine/issues"

[project.optional-dependencies]
test = ["pytest", "ruff", "mypy", "docutils", "types-docutils", "sphinx"]
docs = ["sphinx", "sphinx-rtd-theme"]

[tool.setuptools.package-data]
asciidoctrine = ["grammar.lark"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
norecursedirs = ["vendor", "venv", ".git", "docs"]

[tool.ruff]
line-length = 88
target-version = "py39"
exclude = ["vendor", "venv", ".git"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.12"
strict = true
packages = ["asciidoctrine"]
mypy_path = "src"
ignore_missing_imports = true
